### ISSUE TITLE
Typo in default value for schacHomeOrganization

### ISSUE THREAD

**Issue by andreaceccanti** [rcauth-eu/aarc-delegation-server#1]
Hi,

just wanted to warn about a possible typo:

schacHomeOrganisation -> schacHomeOrganization

https://github.com/rcauth-eu/aarc-delegation-server/blob/6172bb7f53f7009d23396ace04ecc48ec5edf57a/delegation-server/src/main/java/org/delegserver/oauth2/DSDefaultDNGeneratorConfiguration.java#L34 

Any resulting issue is likely shielded by a proper configuration file being in place.

**Comment by msalle** [comment]
This is fixed in the [0.2.0 release](https://github.com/rcauth-eu/aarc-delegation-server/releases/tag/v0.2.0)
