### ISSUE TITLE
Content-type not set in Token response

### ISSUE THREAD

**Issue by andreaceccanti** [rcauth-eu/aarc-delegation-server#2]
Hi,

the token response returned by the RCAuth delegation server does not include the Content-Type header, while it should. This confuses clients that use the header to know how to deserialize the response body.

**Comment by msalle** [comment]
Hi,
this is fixed in upstream in the security-lib dependency. I'm busy updating the external dependencies to the latest stable version which will also fix this issue. If it is a really blocking issue I can probably backport the fix.

**Comment by andreaceccanti** [comment]
Hi @msalle , not blocking for me, I have an hacky workaround in place, thanks, so no need to hurry.

**Comment by msalle** [comment]
This is fixed in the [0.2.0 release](https://github.com/rcauth-eu/aarc-delegation-server/releases/tag/v0.2.0)
