### ISSUE TITLE
Registration of callback URLs that use the http: scheme with localhost as the hostname is not allowed

### ISSUE THREAD

**Issue by NicolasLiampotis** [rcauth-eu/aarc-delegation-server#3]
Hi,

Currently, any callback URL that uses the `http:` scheme is deemed as not secure. However, callback URLs using the `http:` scheme should be allowed when specifying `localhost` as the hostname.

**Comment by msalle** [comment]
Hi,
I agree it's preferable (and I will fix it in our port of the upstream OA4MP), but I don't think the specs actually require support for http://localhost/ redirect_URIs:

> ...MUST NOT use the http scheme unless the Client is a native application, in which case it MAY use the http: scheme with localhost as the hostname.

**Comment by msalle** [comment]
This is fixed in the [0.2.0 release](https://github.com/rcauth-eu/aarc-delegation-server/releases/tag/v0.2.0)
