### ISSUE TITLE
Successful client registration page does not include callback URLs

### ISSUE THREAD

**Issue by NicolasLiampotis** [rcauth-eu/aarc-delegation-server#4]
Hi,

Currently, the successful client registration page provides information about the client ID and secret. It would be useful to also include the list of registered callback URLs.

**Comment by msalle** [comment]
Right, I was thinking of returning a JSON with all the settings, since the callback URLs is only one of those. Does that make sense?

**Comment by msalle** [comment]
Hi @NicolasLiampotis 
would something like this be good? (The problem with a JSON is that it's not always automatically parsed, so a human readable page is then better).

![Screenshot-2019-5-8 Registration Successful ](https://user-images.githubusercontent.com/339484/57386265-4e1baf80-71b4-11e9-86bd-2b6b2b8d8248.png)

**Comment by NicolasLiampotis** [comment]
Hi @msalle  
This looks good to me and I agree that the human readable page is better than a JSON. Would it make sense to also include the Refresh Token lifetime (probably only if a value has been specified during registration)?

**Comment by msalle** [comment]
Hi @NicolasLiampotis,
I agree, but note that this is the one for the delegation server, which does not support the refresh tokens. For the master portal, it's indeed included.
Would you prefer to have a row with an empty value, or skip the whole row completely, in case it's not set?

**Comment by NicolasLiampotis** [comment]
Hi @msalle, 

> Hi @NicolasLiampotis,
> Would you prefer to have a row with an empty value, or skip the whole row completely, in case it's not set?

I think it would be better to include a Refresh Token lifetime row with an empty value to make things more clear.

**Comment by msalle** [comment]
I agree.
This will be part of the 0.2.0 versions of the MasterPortal and DelegationServer

**Comment by msalle** [comment]
Fixed in the [0.2.0 release](https://github.com/rcauth-eu/aarc-delegation-server/releases/tag/v0.2.0)
